### ISSUE TITLE
Angular 4.3+ support

### ISSUE THREAD

**Issue by jscharett** [leandreck/spring-typescript-services#53]
Angualr 4.3 introduced [HttpClient](https://github.com/angular/angular/commit/37797e2) and Angular 5 has [deprecated](https://github.com/angular/angular/pull/18906) `@angular/http`.  Can we get support for  these?

**Comment by mkowalzik** [comment]
Sure, I look into it.
In the meantime you can specify your own template and provide it to the @TypeScriptEndpoint annotation.

**Comment by jscharett** [comment]
Cool.  Can you direct me on how to provide my own template.  I'm not familiar with FreeMarker; do I just put it in a specific location or do I need to set a pom attribute to point to it?  Thanks

**Comment by mkowalzik** [comment]
You can put it on the classpath and provide it via annotation property:

@TypeScriptEndpoint(template = "/some/classpath/value/where/your/template/is/service.ftl")
@RestController
@RequestMapping("/api")
public class Endpoint {

    @RequestMapping(value = "/int", method = GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody int getInt() {
        return 1;
    }
}

You can find the default template here: https://github.com/leandreck/spring-typescript-services/blob/development/annotations/src/main/resources/org/leandreck/endpoints/templates/typescript/service.ftl

I bet most of the template will be quite obvious to you.

**Comment by jscharett** [comment]
Thanks!

**Comment by jscharett** [comment]
Curious if this will land in 0.2.0 or not as its marked ready.

**Comment by mkowalzik** [comment]
It will, it is almost done :-). Would you like to take a look at it before it will be released?

**Comment by jscharett** [comment]
yeah, sure.  do you have it in a branch?

**Comment by mkowalzik** [comment]
yes and I also created a pull request, so you can comment on it.

**Comment by mkowalzik** [comment]
@jscharett please let me know whether or not this fits your needs - same for RequestParam

**Comment by jscharett** [comment]
@mkowalzik Working on integrating.  So far everything is looking good. Thanks!
