### ISSUE TITLE
lombok support

### ISSUE THREAD

**Issue by jscharett** [leandreck/spring-typescript-services#54]
It would be nice to get support for lombok so that when defining model, I can just annotate the class as @Data and not have to specify all the getters and setters.

**Comment by mkowalzik** [comment]
You took the words right out of my mouth :-).
We just switched from generated to lombok dtos and I Long for that feature.

**Comment by jscharett** [comment]
So, is this merely a wish list or something that def coming?  I'll help if I can, but honestly, I'm not a java dev and currently don't know what it would take to impl.

**Comment by mkowalzik** [comment]
No, it was fairly simple to add support for Data, Value and Getter on Types. (see https://github.com/leandreck/spring-typescript-services/commit/cb9ef8ad57912bdf1d9bff47745c196f7de6587b)

Getter on Fields will take an additional hour or so.
I think both will be in Version 0.2.0
