### ISSUE TITLE
support @RequestParam (Optional<T>)

### ISSUE THREAD

**Issue by jscharett** [leandreck/spring-typescript-services#59]
Not seeing any of the optional QueryString params being passed to my get calls.  Can we get support?

**Comment by jscharett** [comment]
Looks like this was recently added and closed under #55.  When might we see a new version pushed?

**Comment by mkowalzik** [comment]
We will release a new Version in the next couple of days no later than Tuesday.

**Comment by jscharett** [comment]
Awesome!  Thanks

**Comment by jscharett** [comment]
Looks like the TypeScript signature is not correct with regards to Optional RequestParams.  For example:

`public RulePagedContent getRules(@RequestParam("pageSize") Optional<Integer> pageSize, @RequestParam("pageIndex") Optional<Integer> pageIndex,
			@RequestParam("sortFields") Optional<String> sortFields,
			@RequestParam("filter") Optional<String> filter, @Context HttpServletRequest request) throws Exception {`

will generate

`public getRules(pageSize: Optional, pageIndex: Optional, sortFields: Optional, filter: Optional): Observable<RulePagedContent> {`

I would expect it to generate

`public getRules(pageSize?: Number, pageIndex?: Number, sortFields?: string, filter?: string): Observable<RulePagedContent> {`

The `Optional` signature should be represented by the `?` following the parameter name and the Type definition passed to Optional should be set as the TypeDef for the parameter.  The way its working now, all the method expects 4 required parameters of type Optional

**Comment by jscharett** [comment]
Another issue I am seeing, at least with trying to work around the issue, is that the HttpParams.set requires the data to be a string.  So, for my previous example, when trying to pass in a Numeric value, it needs to be cast down to a string.

Also, if passing in null, for a particular parameter, it sets the value in the value in the HttpParams which in turn passes that in the url

`...rules?pageSize=null&pageIndex=null&sortFields=null&filter=cat`

I would expect that it just passed the set values like so

`...rules?filter=cat`

**Comment by jscharett** [comment]
So, I was about to workaround the issue by adjusting the service.ftl, though my solution is not as nice as I'd like as it loses some of the type definitions.

`public ${method.name}(<#list method.pathVariableTypes as variable>${variable.fieldName}: ${variable.type}<#sep>, </#sep></#list><#if method.queryParameterTypes?size gt 0><#if method.pathVariableTypes?size gt 0>, </#if>...options</#if>): Observable<${method.returnType.type}> {
        const url = this.serviceBaseURL + '${expandedURL}';
        const paramNames = [<#list method.queryParameterTypes><#items as queryParam>'${queryParam.fieldName}'<#sep>, </#sep></#items></#list>];
        const params = this.getHttpParams(paramNames, <#if method.queryParameterTypes?size gt 0>options<#else>[]</#if>);
        return this.httpClient.get<${method.returnType.type}>(url, {params: params})
            .catch((error: Response) => this.handleError(error));
    }`

Essentially, I list all the path variables first, followed by the `requestBodyType` (depending on method type) followed by a rest parameter if there are any `queryParameterTypes`.  I had hoped deconstruct the rest parameter as indicated on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) like so

`function f(...[a, b, c]) {
  return a + b + c;
}`

but it does not appear to be supported in Typescript.  Either that, or I'm just not doing it right.

**Comment by mkowalzik** [comment]
I think we can find a solution to this problem but I won't be able to help before next week.

**Comment by jscharett** [comment]
Np.  I am working around the issue so I am good.  I found the answer to my problem with rest deconstructing was simply to use the optional signature with the `?`.  Long day yesterday.  Anyhow, the only issue that I'm not able to resolve using a custom template are the Optional types.  I'm currently just forcing them to `: any`, but having the actual type would be preferable.
