### ISSUE TITLE
Support Optional RequestBody in POST/PUT etc

### ISSUE THREAD

**Issue by jscharett** [leandreck/spring-typescript-services#61]
It would seem that requestBody is not a [requirement](http://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0276.html) of a POST/PUT.  We're running into this issue with respect to doing a file upload.  The compiler fails as there is no requestBody.

**Comment by mkowalzik** [comment]
Could you please explain this with a little example?

**Comment by jscharett** [comment]
So, we have a method to upload a file like so

```
@RequestMapping(value = "/list/{id}/upload", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
public List<Items> uploadListItems(
	@PathVariable("id") long id,
	@RequestParam("uploadfile") MultipartFile uploadfile,
	@Context HttpServletRequest request
) throws Exception {
	...
}
```

In this scenario, we are using POST but are not using the RequestBody annotation.  This seems to be true of many of the online Spring upload examples I've seen, where the MultipartFile is mapped using the RequestParam or RequestPart annotation.  According this [stackoverflow](https://stackoverflow.com/questions/7323958/are-put-and-post-requests-required-expected-to-have-a-request-body) post, it would seem that the RequestBody, while preferred, is not required of a PUT/POST.  However, the current service.ftl file seems to expect there to be a body for PUT/POST, which causes the tempalte enginge to fail

```
public ${method.name}Post(<#list method.methodParameterTypes as variable>${variable.fieldName}: ${variable.type}<#sep>, </#sep></#list><#if method.pathVariableTypes?size gt 0>, </#if>${method.requestBodyType.fieldName}: ${method.requestBodyType.type}): Observable<${method.returnType.type}> {
```

**Comment by mkowalzik** [comment]
Hi @jscharett,
I think the newest snapshot should do it.
I will add some additional tests tomorrow and release it in 0.3.0.
